services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_THREADS=8     # ใช้ให้เต็มคอร์
      - OMP_NUM_THREADS=8
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      # ใช้ CLI ของ ollama เช็คว่า daemon ตอบแล้ว (ไม่พึ่ง curl/wget)
      test: ["CMD", "sh", "-lc", "ollama list >/dev/null 2>&1"]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 120s
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped

volumes:
  ollama: