server:
  port: 8080

spring:
  ai:
    ollama:
      base-url: http://host.docker.internal:11434
      init:
        pull-model-strategy: never
      chat:
        options:
          model: llama3.2:latest
          temperature: 0.2
          num-predict: 128
          num-ctx: 1024